name: Build and Deploy Apps (Incremental & Full)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Select build mode: "incremental" or "full"'
        required: true
        default: 'incremental'

jobs:
  call-template:
    uses: tejkumar11111/pipeline/.github/workflows/build-and-deploy-template.yml@main
    with:
      mode: ${{ github.event.inputs.mode }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
